[server]
host = "127.0.0.1"
port = 3000

[database]
url = "sqlite://flux.db?mode=rwc"

[plugins]
directory = "./plugins"

[eventbus]
capacity = 1024

[mqtt]
port = 1883
workers = 2

[logging]
level = "info"
