[package]
name = "flux-types"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.43", features = ["serde", "wasmbind", "clock"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde", "js"] }

